- name: Install Node.js, npm, and tsx on Debian
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - git
        state: present

    - name: Add NodeSource APT key
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
      args:
        creates: /usr/share/keyrings/nodesource.gpg

    - name: Add NodeSource repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/nodesource.list
        content: |
          deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
        mode: '0644'

    - name: Update apt cache after adding NodeSource repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Node.js and npm
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Install tsx globally via npm
      community.general.npm:
        name: tsx
        global: true
