- name: Setup MariaDB (MySQL compatible) with medium_db db and remote login
  become: yes
  hosts: inno
  vars:
    db_user: user
    db_pass: password    
    db_name: test_db

  tasks:
    - name: Install MariaDB and dependencies
      ansible.builtin.apt:
        name:
          - mariadb-server
          - mariadb-client
          - python3-mysqldb
        state: present
        update_cache: yes

    - name: Ensure MariaDB service is started and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create MySQL user
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "*.*:ALL"
        host: "%"
        state: present

    - name: Create database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Enable remote login to MariaDB
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mariadb

  handlers:
    - name: Restart mariadb
      ansible.builtin.service:
        name: mariadb
        state: restarted
